---
repository:
  name:                                  "ansible-role-stern"
  description:                           "Ansible Role - Stern"
  # homepage:                            https://example.github.io/
  topics:                                "automation, stern, ansible-role"
  private:                               false
  has_issues:                            false
  has_projects:                          false
  has_wiki:                              false
  has_downloads:                         true
  default_branch:                        master
  is_template:                           false
  allow_squash_merge:                    false
  allow_merge_commit:                    false
  allow_rebase_merge:                    false
branches:
  - name:                                master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews:           true
        require_code_owner_reviews:      false
        dismissal_restrictions:
          users:                         []
          teams:                         []
      required_status_checks:
        strict:                          true
        contexts:                        [ "sample" ]
      enforce_admins:                    true
      required_linear_history:           true
      restrictions:
        apps:                            []
        users:                           []
        teams:                           []
