---
galaxy_info:
  role_name: stern
  author: Michael Maffait
  namespace: pandemonium1986
  description: Install stern from github repository.
  # company: your company (optional)
  license: MIT
  min_ansible_version: "2.10"
  github_branch: main
  platforms:
    - name: Debian
      versions: ["bookworm"]
    - name: EL
      versions: ["7"]
    - name: opensuse
      versions: ["15.3", "15.5"]
    - name: SLES
      versions: ["15SP3", "15SP5"]
    - name: Ubuntu
      versions: ["jammy"]
  galaxy_tags: ["kubernetes", "tool", "k8s"]
dependencies: []
