---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: molecule-${DKR_IMAGE:-debian12}
    hostname: ${DKR_IMAGE:-debian12}
    image: ghcr.io/pandemonium1986/${DKR_IMAGE:-debian12}:${DKR_TAG:-nightly}
    pull: true
    pre_build_image: true
    tty: true
    override_command: false
    tmpfs:
      - /run
      - /tmp
    privileged: true
provisioner:
  name: ansible
  lint: |
    set -e
    ansible-lint
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
scenario:
  name: default
verifier:
  name: ansible
  enabled: true
