---
# https://github.com/derailed/k9s
k9s_cache_path:        "/var/cache/github"
k9s_installation_path: "/opt/github/k9s"
k9s_checksum:          "sha256:42d8aef6b839a9bc60de29d2461521596ce2d1f66347dbf5196983229cfeafd2"
k9s_version:           "v0.22.1"
