---
# https://github.com/derailed/k9s
k9s_cache_path:        "/var/cache/github"
k9s_installation_path: "/opt/github/k9s"
k9s_checksum:          "sha256:9a57de7b65c3b7be315e2a187c515fee72245f8ef789de5eb7cca2b7e2e2d158"
# k9s_checksum:          "sha256:18d68347b5f6427724a9b5645c211c61678a00138ad050edfa4aa8e92a87d042"
k9s_version:           "v0.24.8"
# k9s_version:           "v0.24.9"
